### ISSUE TITLE
_trace_write_semihosting_debug buffer overrun

### ISSUE THREAD

**Issue by andrea-marchini** [micro-os-plus/cmsis-plus#11]
(hope it's the right place for reporting)

Hi, in the diag/trace-semihosting.cpp, line 122:

std::size_t n = ((togo < sizeof(tmp)) ? togo : sizeof(tmp));

should be:

std::size_t n = ((togo < (sizeof(tmp)-1)) ? togo : (sizeof(tmp)-1));

Otherwise, at line 128:

tmp[i] = '\0';

You have a buffer overrun.

Ciao

Andrea

**Comment by ilg-ul** [comment]
oops!

thank you, I'll fix it.

**Comment by ilg-ul** [comment]
https://github.com/micro-os-plus/micro-os-plus-iii/commit/78165675af0b3c6e6541c778a2aac18a357fa559

**Comment by ilg-ul** [comment]
fixed on 2017-07-03.
