### ISSUE TITLE
malloc & errno

### ISSUE THREAD

**Issue by imatic01** [micro-os-plus/cmsis-plus#14]
I've noticed this problem while trying to get exceptions to work. The issue is that during early startup, free store gets initialized and after it os_run_init_array() gets called. If any of the functions inside it try to use malloc (possibly something else as well) which uses current thread's errno variable, we get a problem because at this point no thread has been scheduled to run.

**Comment by ilg-ul** [comment]
thank you for the bug report.

I'll investigate and find a solution.

**Comment by imatic01** [comment]
I wanted to let you know that I did manage to get things working by assigning a static thread to os::rtos::scheduler::current_thread_ just before the call to os_run_init_array(). That solved the malloc problem but then the library sent some request to __register_exitproc using unsupported __et_cxa exit type, but since my code never actually exits I just ignored those calls and after a switch to regular libc (from nano) things work, at least for some of the simpler examples I tried. I guess nano lib doesn't support exceptions at all as every throw resulted with system reset.

Best regards

**Comment by ilg-ul** [comment]
please try the new beta version available in the develop branch.

I initialised the `current_thread_` pointer to a tiny thread; I'm not particularly happy with the solution, but it seems functional.

https://github.com/micro-os-plus/micro-os-plus-iii/commit/4c02efe206bf6df2ef8833ff1bb407d493028ea4

**Comment by ilg-ul** [comment]
as for the other problems, the nano version might be too simple; if the plain newlib works, we'll probably leave it like this until I'll have more time to do tests with exceptions.

**Comment by imatic01** [comment]
I was thinking that maybe it would make sense to expand errno into plain old global static int until scheduler gets started. Technically there are no threads in the system at that point so why insist on per thread errno? I will try the new version on monday as my code is on another computer...

**Comment by ilg-ul** [comment]
> expand errno into plain old global static int until scheduler gets started

how would you do it?

adding an `if` in the function is not exactly elegant.

**Comment by imatic01** [comment]
Well, if branching presents a problem then nothing better comes to mind currently. Using function pointers would be no better then the current solution.

**Comment by ilg-ul** [comment]
branching does not present a problem, but is it worth? except very few moments during inits, the branch will always take the same path.

we can also add an extra indirection level via a pointer, and initially point to a short function that addresses a static int and later make it point to the one that uses the current thread, but the current inline solution will no longer work. the same question: is it worth?

the cost now is 3 words. it is not 0, but I guess it is the best we can get.

**Comment by imatic01** [comment]
I am aware of that, and I agree with your reasoning here. One could argue that the compiler would be smart enough to figure out what is going on, but without some hard checking there is no way to know. It's interesting, to me, how even with all these new additions into language I don't see an easy way to solve this problem. There is probably some "very smart" solution using templates :-)

**Comment by ilg-ul** [comment]
this is a run-time decision, I'm afraid no such smart solution can be found.

**Comment by imatic01** [comment]
But it's actually just a true / false decision so that is why I mentioned templates.

**Comment by ilg-ul** [comment]
templates are for compile time polymorphism, while the decision is at run time.

**Comment by imatic01** [comment]
I tried compiling the changes and this is what i get:

../RTOS/micro-os-plus-iii/src/rtos/os-core.cpp:112:73: error: 'int os::rtos::thread::errno_' is protected within this context
       static_assert(offsetof(tiny_thread_t, errno_) == offsetof(thread, errno_), "adjust tiny_thread_t members");
                                                                         ^
In file included from ../RTOS/micro-os-plus-iii/include/cmsis-plus/rtos/os.h:96:0,
                 from ../RTOS/micro-os-plus-iii/src/rtos/os-core.cpp:28:
../RTOS/micro-os-plus-iii/include/cmsis-plus/rtos/os-thread.h:1557:20: note: declared protected here
       int errno_ = 0;
                    ^
../RTOS/micro-os-plus-iii/src/rtos/os-core.cpp:112:7: error: static assertion failed: adjust tiny_thread_t members
       static_assert(offsetof(tiny_thread_t, errno_) == offsetof(thread, errno_), "adjust tiny_thread_t members");
       ^~~~~~~~~~~~~

**Comment by ilg-ul** [comment]
are you sure you updated all files affected by this patch? https://github.com/micro-os-plus/micro-os-plus-iii/commit/ff51dc02d446c0c507dbc0076fc16892cc3f2b23

**Comment by imatic01** [comment]
My bad. It works now. Remaining problem is `assert(type == __et_atexit); ` inside `__register_exitproc`. I tried defining _LITE_EXIT on the command line but it didn't help. Probably `newlib` doesn't take that into account at all. For now I just ignore calls with `__et_cxa` requests...

**Comment by ilg-ul** [comment]
> Remaining problem is assert(type == __et_atexit)

please enter a separate issue for this, so I can track it.

**Comment by ilg-ul** [comment]
fixed on 2017-10-06.
