### ISSUE TITLE
atexit & newlib

### ISSUE THREAD

**Issue by imatic01** [micro-os-plus/cmsis-plus#15]
When linking against `newlib`, `atexit` is called using parameter types that are currently not supported. Specifically `assert(type == __et_atexit)` inside `__register_exitproc` function fails.

**Comment by ilg-ul** [comment]
The local implementation of `atexit()` is very lite, and is intended for very tight environments, generally using newlib-nano.

When linking agains newlib, the standard `atexit()` should be used.

I added `OS_INCLUDE_ATEXIT_STATIC` that must be explicitly used to include the lite version. When exceptions are enabled, this options is ineffective, and the standard `atexit()` is always used.

**Comment by ilg-ul** [comment]
Fixed on 2018-03-27.
