### ISSUE TITLE
Alignment for memory allocators

### ISSUE THREAD

**Issue by imatic01** [micro-os-plus/cmsis-plus#18]
I have to manage an external device that requires 64 byte alignments in memory, and I was wondering if you have any plans on making this comment come true?

`// TODO: consider `alignment` if > block_align.
`

Best regards,
Ivica

**Comment by ilg-ul** [comment]
where exactly is this?

**Comment by imatic01** [comment]
`void* first_fit_top::do_allocate (std::size_t bytes, std::size_t alignment)`
`void* lifo::do_allocate (std::size_t bytes, std::size_t alignment)`
`alignment` parameter is not considered at all...

**Comment by ilg-ul** [comment]
aha. could you suggest a PR?

**Comment by imatic01** [comment]
OK, I will look into it...

**Comment by ilg-ul** [comment]
Sorry for the delay...

Fixed on 2018-03-27.
