### ISSUE TITLE
bool event_flags::_try_wait in the file "cmsis-plus/src/rtos/os-evflags.cpp"

### ISSUE THREAD

**Issue by valentingorelov** [micro-os-plus/cmsis-plus#2]
It seems that the function 

```
bool event_flags::_try_wait (flags::mask_t mask, flags::mask_t* oflags,
                            flags::mode_t mode)
```

in the file "cmsis-plus/src/rtos/os-evflags.cpp"
ignores the "clear" value of the "mode" argument. Flags are always cleared.

**Comment by ilg-ul** [comment]
oops!

I refurbished the event_flags class, please check https://github.com/micro-os-plus/cmsis-plus/commit/333b6595f9b1bda7597fbe90788678db8ad5d919 and let me know if you have further suggestions.

thank you for your help.
