### ISSUE TITLE
Advanced memory management features

### ISSUE THREAD

**Issue by ilg-ul** [micro-os-plus/cmsis-plus#3]
I'm working on adding more memory management features to µOS++.

The plan is the following:
- there is a class `os::estd::memory_resource`, which defines the allocator API; the API is based on the standard one (http://en.cppreference.com/w/cpp/experimental/memory_resource) but with some extensions
- from this class I derived a class `os::estd::memory::newlib_nano_malloc`, which implements the allocation policy used by newlib nano (the class is polymorphic)
- an instance of this class, initialised with the entire heap space (_Heap_Begin - _Heap_limit) is created after the hardware initialisation sequence, and a pointer to it is stored in a global location, available with `os::estd::get_default_resource()`
- all C++ `new` and `delete` operators are implemented on top of the virtual `os::estd::get_default_resource()->allocate()` and `os::estd::get_default_resource()->deallocate()`, but braced with scheduler critical sections, to protect concurrent accesses from multiple threads
- also on top of those functions I implement `malloc()` and `free()`, so C applications use the same allocator, with the same critical sections

The advantages of this scheme:
- the allocator is very clearly defined
- the allocator is under full control of the developer

Defining another allocator requires:
- defining another class derived from `os::estd::memory_resource`
- redefining the new `os_startup_initialize_free_store()`
- in this function, the new derived class is created, and a pointer to it is set with `os::estd::set_default_resource()`

In addition to the application allocator, µOS++ defines a system allocator. It uses the same mechanism, but the identity of this allocator is kept in a separate global variable, accessible via `os::rtos::memory::get_default_resource()`. By default, this allocator is initialised with the same memory_resource derived object as the application allocator.

From this system allocator the services that may require additional memory (like thread stacks, queues, memory pools) get their resources.

It is recommended to allocate (statically or even dynamically) a separate RAM area, and define a separate system allocator operating on this area; this has several advantages:
- protects the system area from possible application fragmentation
- allow to use different allocation policies for the application and for the system

In addition to this, for ultimate configurability (actually as usual for C++ objects), it is possible to define any number of custom allocators, and use them for each object.

As possible allocator policies, I plan to implement the following:
- LIFO - it deallocates only if the block is the last allocated, coalescing with previous freed blocks, but kept "in limbo" for not being the last; this prevents fragmentation; this policy is useful for system that allocates memory only during startup 
- BLOCK POOL allocator - it allocates fixed sizes blocks; this prevents fragmentation
- a more elaborate variable size allocator, using size specific "bins", to keep track of different size blocks
- FreeRTOS 2 and 4, which are variable size allocators, the second one with free blocks coalescing.

Any suggestions are welcome.

@carlosdelfino ? @0xc0170 ? @armint ?

**Comment by carlosdelfino** [comment]
I've been visiting the project looking for a way to contribute more in programming.

But it's a subject where I'm an apprentice, and I honestly still doubt how to contribute beyond the translations I'm doing.

I'm going to dedicate a little bit to the topics related to memory allocation and deallocation in C ++ in Cortex-M today.

Any reading clipping would be interesting for the focus of this project.

**Comment by ilg-ul** [comment]
the memory management features are now fully implemented, you can experiment and let me know the results.

unfortunately the user manual is not yet ready (the memory management chapter is next in line).

if you have questions, don't hesitate to ask.

**Comment by carlosdelfino** [comment]
What worries me is exactly the lack of a question.

I've never programmed this level with an RTOS, so I'm still learning. And the project I have in mind now, demands multiple cores.

Is there anything I could focus on in this sense? Distribution of tasks by different cores? I have not tried it yet in QEMU intend to start on Monday back to QEMU when finished buildings.

I prefer the feeling of having a thousand questions than having none.

I saw that you created a test file at https://github.com/micro-os-plus/micro-os-plus-iii/blob/e81431ed5c96edb6d620f79e023c401190204c21/test/rtos/src/test-cpp-mem.cpp

Should I start with it? It would be interesting to have some example integration tests that we could run in QEMU, so I run in my environment and I'm going to study how things are done.

And as you have seen my environment is full of surprise, without something happening out of the predicted.
: D

**Comment by ilg-ul** [comment]
> the project I have in mind now, demands multiple cores.

I seriously doubt so, as far as I know, Cortex-M cores are not designed to access a single memory from multiple cores. if your application really does, the cores will probably be Cortex-A, and run a multi-core version of the linux kernel.

> Is there anything I could focus on in this sense? Distribution of tasks by different cores? 

I don't know, I don't believe this is a realistic approach. 

> test-cpp-mem.cpp

this file is part of one of the tests, you can try to build the `test-rtos-{debug|release}` config and run the result on the emulated f4discovery.

**Comment by carlosdelfino** [comment]
NXP has a two-color microcontroller, and I'm not finding another one in Texas that's three-color.

The equipment that I am researching would be necessary 4 internal or external colors, in the first prototype will be external 2 being Cortex-M and 2 being xTensa will need a mechanism of synchronism, but will be independent of the RTOS per hour.

This is the NXP with two colors:
http://www.nxp.com/products/microcontrollers-and-processors/arm-processors/lpc-cortex-m-mcus/lpc-cortex-m4/lpc4300-cortex-m4-m0:MC_1403790133078

![image](https://cloud.githubusercontent.com/assets/369056/20222502/564d9f54-a814-11e6-9174-0e000e6f15f3.png)

The Cortex-M was built thinking of multicore, little known but exists.

**Comment by ilg-ul** [comment]
ah, I know LPC4300, but it is not really multi-core, it is asymmetric, the M0 is actually a coprocessor, running under the M4 control. the M0 is usually used as a smart watch-dog, or as a safe bootstrap, the hard work is done by the M4.

**Comment by carlosdelfino** [comment]
I understand, as defined in the new ARMv8-M such tactic becomes unnecessary if I am not mistaken, that is to have a second core as responsible for the first.

But can not this second core be used for secondary tasks? The LPC43xx seems to suggest such a use, and there are models that have 2 cortex-m0 and 1 cortex-m1, I understand that the cortex-m0 acting as coprocessor may be responsible for secondary activities in the system, in my case for example as a datalogger in A GPS and / or beacon on a high demand wireless system.

What prevents you from having such a multi-color approach? Are you unaware of the use of multiple colors in microcontrollers?

**Comment by ilg-ul** [comment]
each core is obviously responsible for a different task, but it is a problem of hierarchy.

in a symmetrical design, any task can be scheduled on any core, even started on one and continued on another. 

> a datalogger in A GPS ... the use of multiple cores 

you probably are not aware of the computing power of modern microcontrollers.

a properly written application, which does not perform complex computations and always suspends a thread while waiting for an event, on average uses 10-20% of the CPU time, even on a smaller core, performing multiple tasks.

and chips are so cheap today, that, if you want total separation, you can use multiple microcontrollers, connected on a bus.

let's take the datalogger application: where do you think most of the time is consumed? probably waiting for the storage to write the blocks; you don't need much processing power for this (I did several dataloggers, including flight data recorders, and all had similar problems; one application had 18 threads, including measurements, radio communication, logging, and even so, on high activity moments, the CPU was still mostly waiting).
