### ISSUE TITLE
Confused about yotta related files

### ISSUE THREAD

**Issue by kblomqvist** [micro-os-plus/cmsis-plus#4]
There's `.yotta_ignore` and `module.json` files in repo, but I couldn't find the project to be installable via yotta.

**Comment by ilg-ul** [comment]
unfortunately ARM abandoned yotta, and the xPacks will no longer stored on the yotta server, but on the <s>nlm</s> npm server.

I'll remove the yotta related files in the next release.

**Comment by kblomqvist** [comment]
Forgive my ignorance but what's nlm server?

**Comment by ilg-ul** [comment]
sorry for the typo, it is the [npm](https://www.npmjs.com) server.
