### ISSUE TITLE
Add override keyword to virtual functions

### ISSUE THREAD

**Issue by LnnrtS** [micro-os-plus/cmsis-plus#48]
Compiling on gcc 5.4.1 with "-Wsuggest-override" and "-Werror=suggest-override" fails.

Adding the override keyword for

```
char_device_impl::do_lseek
char_device_impl::do_sync
tty_impl::do_isatty
```

fixes this for me.

**Comment by ilg-ul** [comment]
Thank you, Lennart, please check the develop branch.
