### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by LnnrtS** [micro-os-plus/cmsis-plus#54]
I tried to fix #50 but cannot get a development environment running. For regular projects, I copied the source code into my makefile based projects. Now I would like to just clone the `xpack` branch, specify a port (cortex-m or posix/linux) and get and everything setup with an empty `os_main` or some unittests running. Preferably without the need of an IDE. What is the most straightforward way to do that?

I was briefly looking into xpacks but It doesn't seem that using them would do what I need..

**Comment by ilg-ul** [comment]
For general discussions please use the project forum (https://www.tapatalk.com/groups/xpack/os-f4/), and keep the GitHub issues **only** for bugs that I need to keep track of.

**Comment by LnnrtS** [comment]
I will check the forum. Still it would be great if the readme would provide some information on that

**Comment by ilg-ul** [comment]
The forum is empty for now, you'll have the honour to post the first messages ;-)

> it would be great if the readme would provide some information on that

Yes, right. :-(

Let's hope that in the next project iteration we'll have a better documentation.

**Comment by ilg-ul** [comment]
I created a first message with project links in the µOS++ section of the forum.

Please post a message in the General Discussions forum with the previous question, and possibly with further questions.

**Comment by ilg-ul** [comment]
> I tried to fix #50

how exactly did you try to fix it? please comment in the #50 issue.
