### ISSUE TITLE
printf() calls do not print float/double values

### ISSUE THREAD

**Issue by ilg-ul** [micro-os-plus/cmsis-plus#6]
attempts to print `float` values usually result in printing 0.0, while printing `double` values results in printing garbage.

apparently all `printf()` related calls are affected, including `snprintf()`, so it is easy to test.

**Comment by ilg-ul** [comment]
the problem was not related to `printf()`, but to all functions using variable arguments. more specifically, the implementation of the `va_arg()` macro not only expects the stack to be aligned at 8 bytes for float/double variables, but silently aligns it.

if at the moment of the call the stack was not 8-bytes aligned, this results in fetching wrong values from the stack.

the solution is to guarantee that the initial thread stack is aligned at 8-bytes.

two notes:

- the current Cortex-M cores work even if the stack is aligned only at 4-byte limits, so the implementation of the `va_arg()` macro seems a bit extreme

- the current ARM IHI 0042F document, from 24th Nov. 2015, describing the _Procedure Call Standard for the ARM Architecture_, at 5.2.1.2, states _SP mod 8 = 0. The stack must be double-word aligned._

there were two commits to fix this issue:

- https://github.com/micro-os-plus/micro-os-plus-iii-cortexm/commit/e8f10ed0f749f562c2a653697751d6c1646b2246, aligning the thread stack
- https://github.com/micro-os-plus/micro-os-plus-iii-cortexm/commit/525c7dbad83bbd27cb888e8f478db00a93a7b810, adding asserts for both the thread stack and the MSP stack.

**Comment by bitFiedler** [comment]
now the fix prevent a hard fault, but do not show any float or double value in the string output.

for instance, if you do 
printf("test: %f \r\n", 2.333f);

the output looks like -> "test:  "
the value is missing.

the same is with %g.

**Comment by ilg-ul** [comment]
either disable the use of newlib-nano, or enable the use of float for `printf()` (in the linker options).

**Comment by bitFiedler** [comment]
that was the problem, newly-nano was not enabled for float values.
now I can confirm that your fix works for me.

thanks a lot!

**Comment by ilg-ul** [comment]
ok, in this case I'll make the new release.

**Comment by ilg-ul** [comment]
fixed on v6.3.11.
